spring.application.name=backend
spring.main.banner-mode=off

# Lazy loading para arrancar en < 2 segundos
#spring.main.lazy-initialization=true

# Seguridad
jwt.secret=${JWT_SECRET}
jwt.refresh-expiration-ms=86400000

# MapTiler
maptiler.api.key=${MAPTILER_KEY}

# Admin Inicial
initial.admin.username=${INITIAL_ADMIN_USERNAME}
initial.admin.password=${INITIAL_ADMIN_PASSWORD}
initial.admin.email=${INITIAL_ADMIN_EMAIL}

# Jackson
#spring.jackson.serialization.write-dates-as-timestamps=false

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
