name: Restify Local Deployment

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    name: Build and Run Docker Locally
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Este paso crea el archivo .env dinámicamente en cada ejecución
      - name: Create .env file
        shell: powershell
        run: |
          @'
          ${{ secrets.ENV_FILE }}
          '@ | Out-File -FilePath .env -Encoding utf8

      - name: Restart Docker Containers
        shell: powershell
        run: |
          docker-compose down
          docker-compose up --build -d
