INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_ADMIN');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_USER');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_GUEST');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_OWNER');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_WAITER');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_COOK');
INSERT IGNORE INTO user_roles (name) VALUES ('ROLE_DRIVER');